import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.overview": "Overview",
    "nav.profile": "Child Profile",
    "nav.development": "Development",
    "nav.routines": "Daily Routines",
    "nav.robot": "Robot Controls",
    "nav.gallery": "Moments Gallery",
    "nav.alerts": "Alerts",
    "nav.insights": "AI Insights",
    "nav.caregivers": "Caregivers",
    "nav.settings": "Settings",
    "nav.logout": "Logout",
    
    // Overview
    "overview.title": "Welcome Back! 👋",
    "overview.subtitle": "Here's what's happening with Odaisa today",
    "overview.sleep": "Sleep Last Night",
    "overview.meals": "Meals Today",
    "overview.active": "Active Time",
    "overview.development": "Development Score",
    "overview.liveFeed": "Live Camera Feed",
    "overview.milestones": "Recent Milestones",
    "overview.activity": "Weekly Activity Hours",
    "overview.sleepPattern": "Weekly Sleep Pattern",
    "overview.alerts": "Recent Alerts & Updates",
    "overview.viewAll": "View All",
    "overview.currentActivity": "Current Activity:",
    "overview.playingWithToys": "Playing with toys",
    "overview.firstSteps": "First Steps!",
    "overview.tookSteps": "Took 5 independent steps",
    "overview.newWords": "New Words",
    "overview.wordsThisWeek": "+15 words this week",
    "overview.drawing": "Drawing",
    "overview.firstCircle": "First circle shapes",
    "overview.viewAllMilestones": "View All Milestones",
    "overview.daysAgo": "days ago",
    "overview.ongoing": "Ongoing",
    
    // Child Profile
    "profile.title": "Child Profile",
    "profile.subtitle": "Detailed information and medical records",
    "profile.edit": "Edit Profile",
    "profile.active": "Active Profile",
    "profile.childId": "Child ID:",
    "profile.healthy": "Healthy",
    "profile.dob": "Date of Birth",
    "profile.height": "Height",
    "profile.weight": "Weight",
    "profile.bloodType": "Blood Type",
    "profile.medical": "Medical Info",
    "profile.emergency": "Emergency Contacts",
    "profile.preferences": "Preferences",
    "profile.caregivers": "Caregivers",
    "profile.allergies": "Allergies",
    "profile.medications": "Medications",
    "profile.conditions": "Medical Conditions",
    "profile.vaccinations": "Vaccinations",
    "profile.upToDate": "Up to date",
    "profile.lastCheckup": "Last Checkup",
    "profile.nextCheckup": "Next Checkup",
    "profile.pediatrician": "Pediatrician",
    "profile.scheduleAppt": "Schedule Appointment",
    "profile.primary": "Primary",
    "profile.addContact": "Add Emergency Contact",
    "profile.activities": "Activities & Interests",
    "profile.favoriteActivities": "Favorite Activities",
    "profile.favoriteFoods": "Favorite Foods",
    "profile.care": "Care Preferences",
    "profile.napPrefs": "Nap Preferences",
    "profile.comfortItems": "Comfort Items",
    "profile.temperament": "Temperament",
    "profile.authorized": "Authorized Caregivers",
    "profile.manageAccess": "Manage who has access to Odaisa's dashboard and information",
    "profile.invite": "Invite Caregiver",
    "profile.fullAccess": "Full Access",
    "profile.activeStatus": "Active",
    
    // Development
    "dev.title": "Development & Progress",
    "dev.subtitle": "Track milestones and compare against age-group averages",
    "dev.stats": "Progress & Development Stats",
    "dev.aiInsights": "AI-powered insights and milestone tracking",
    "dev.advanced": "Advanced Analytics",
    "dev.milestones": "Developmental Milestones",
    "dev.growth": "Growth Tracking",
    "dev.activities": "Weekly Activities",
    "dev.percentile": "percentile",
    "dev.recent": "Recent Achievement",
    "dev.prediction": "AI Prediction",
    "dev.next": "Next Milestone",
    "dev.expected": "Expected in",
    "dev.inProgress": "In progress -",
    "dev.heightProgress": "Height Progress",
    "dev.weightProgress": "Weight Progress",
    "dev.growthRate": "Growth Rate",
    "dev.aboveAverage": "above average",
    "dev.healthy": "healthy",
    "dev.totalPlaytime": "Total Playtime This Week",
    "dev.outdoor": "Outdoor Activities",
    "dev.learningTime": "Learning Time",
    "dev.fromLastWeek": "from last week",
    
    // Routines
    "routines.title": "Daily Routines",
    "routines.subtitle": "Track sleep, meals, and daily activities",
    "routines.export": "Export Report",
    "routines.addEntry": "Add Entry",
    "routines.remaining": "Today's Remaining Schedule",
    "routines.upcoming": "Upcoming",
    "routines.sleep": "Sleep",
    "routines.feeding": "Feeding",
    "routines.activities": "Activities",
    "routines.lastNight": "Last Night",
    "routines.weekAverage": "Week Average",
    "routines.interruptions": "Interruptions",
    "routines.excellent": "Excellent",
    "routines.consistent": "Consistent",
    "routines.belowAverage": "Below average",
    "routines.schedule": "Sleep Schedule (Last Night)",
    "routines.completed": "Completed",
    "routines.aiInsight": "AI Insight",
    "routines.hydration": "Hydration Today",
    "routines.todayMeals": "Today's Meals",
    "routines.avgConsumption": "Average Consumption",
    "routines.pending": "Pending",
    "routines.high": "high",
    "routines.medium": "medium",
    "routines.activitySummary": "Activity Summary",
    "routines.totalActive": "Total Active Time",
    "routines.highEngagement": "High Engagement",
    "routines.ofActivities": "of activities",
    "routines.sleepSummary": "Sleep Summary",
    "routines.avgDuration": "Average Duration",
    "routines.consistency": "Consistency Score",
    "routines.quality": "Quality Rating",
    "routines.nutritionSummary": "Nutrition Summary",
    "routines.mealsCompleted": "Meals Completed",
    "routines.hydrationLevel": "Hydration Level",
    "routines.newFoods": "New Foods Tried",
    "routines.thisWeek": "this week",
    "routines.activitySummaryWeek": "Activity Summary",
    "routines.totalActiveTime": "Total Active Time",
    "routines.engagementLevel": "Engagement Level",
    "routines.varietyScore": "Variety Score",
    "routines.good": "Good",
    
    // Robot
    "robot.title": "Robot Controls",
    "robot.subtitle": "Command and schedule your AI childcare assistant",
    "robot.settings": "Robot Settings",
    "robot.status": "Robot Status",
    "robot.online": "Online",
    "robot.battery": "Battery Level",
    "robot.goodCharge": "Good Charge",
    "robot.location": "Current Location",
    "robot.activeTime": "Active Time Today",
    "robot.quickCommands": "Quick Commands",
    "robot.schedule": "Schedule",
    "robot.storyTime": "Story Time",
    "robot.playMusic": "Play Music",
    "robot.lullaby": "Lullaby",
    "robot.playGames": "Play Games",
    "robot.active": "Active",
    "robot.additionalControls": "Additional Controls",
    "robot.volume": "Volume Level",
    "robot.movement": "Movement Mode",
    "robot.follow": "Follow",
    "robot.nightMode": "Night Mode",
    "robot.off": "Off",
    "robot.emergency": "Emergency Controls",
    "robot.stopAll": "Stop All Activities",
    "robot.callCaregiver": "Call Caregiver",
    "robot.addSchedule": "Add New Schedule Item",
    "robot.scheduleOverview": "Schedule Overview",
    "robot.completedTasks": "Completed",
    "robot.pendingTasks": "Pending",
    "robot.upcomingTasks": "Upcoming",
    "robot.tasks": "tasks",
    "robot.task": "task",
    "robot.activityLog": "Today's Activity Log",
    "robot.viewHistory": "View Full Activity History",
    "robot.maintenance": "Maintenance & Updates",
    "robot.lastMaintenance": "Last Maintenance",
    "robot.softwareVersion": "Software Version",
    "robot.nextUpdate": "Next Update",
    "robot.availableNow": "Available Now",
    "robot.updateSoftware": "Update Software",
    "robot.quickActions": "Quick Actions",
    "robot.calibrate": "Calibrate Sensors",
    "robot.testAudio": "Test Audio System",
    "robot.resetHome": "Reset to Home Position",
    "robot.emergencyStop": "Emergency Stop",
    
    // Gallery
    "gallery.title": "Moments Gallery",
    "gallery.subtitle": "AI-captured memories and special moments",
    "gallery.download": "Download Selected",
    "gallery.share": "Share Album",
    "gallery.milestones": "Milestones",
    "gallery.favorites": "Favorites",
    "gallery.specialEvents": "Special Events",
    "gallery.items": "items",
    "gallery.recent": "Recent Captures",
    "gallery.today": "Today",
    "gallery.yesterday": "Yesterday",
    "gallery.thisWeek": "This Week",
    "gallery.thisMonth": "This Month",
    "gallery.loadMore": "Load More Moments",
    "gallery.storage": "Storage Usage",
    "gallery.of": "of",
    "gallery.used": "used",
    "gallery.available": "Available",
    "gallery.autoBackup": "Auto-backup enabled",
    "gallery.capture": "Capture Moment",
    "gallery.filter": "Filter",
    "gallery.total": "Total Moments",
    
    // Alerts
    "alerts.title": "Alerts & Notifications",
    "alerts.subtitle": "Monitor important events and safety alerts",
    "alerts.settings": "Alert Settings",
    "alerts.markRead": "Mark All as Read",
    "alerts.unread": "Unread Alerts",
    "alerts.new": "New",
    "alerts.safety": "Safety Monitoring",
    "alerts.allSystems": "All Systems Ok",
    "alerts.today": "Alerts Today",
    "alerts.notifications": "Notifications",
    "alerts.milestonesWeek": "Milestones This Week",
    "alerts.achievements": "Achievements",
    "alerts.all": "All Alerts",
    "alerts.safetyTab": "Safety",
    "alerts.milestonesTab": "Milestones",
    "alerts.settingsTab": "Settings",
    "alerts.viewDetails": "View Details",
    "alerts.markAsRead": "Mark Read",
    "alerts.highPriority": "high priority",
    "alerts.mediumPriority": "medium priority",
    "alerts.lowPriority": "low priority",
    "alerts.activeMonitors": "Active Safety Monitors",
    "alerts.lastTriggered": "Last triggered:",
    "alerts.armed": "Armed",
    "alerts.emergencySettings": "Emergency Alert Settings",
    "alerts.configureEmergency": "Configure Emergency Alerts",
    "alerts.shareAchievement": "Share Achievement",
    "alerts.viewProgress": "View Progress",
    "alerts.noMilestones": "No milestone notifications yet",
    "alerts.notificationPrefs": "Notification Preferences",
    "alerts.enabled": "Enabled",
    "alerts.disabled": "Disabled",
    "alerts.delivery": "Delivery Methods",
    "alerts.push": "Push Notifications",
    "alerts.email": "Email Alerts",
    "alerts.sms": "SMS (Critical Only)",
    
    // Insights
    "insights.title": "AI Insights & Recommendations",
    "insights.subtitle": "Personalized tips powered by machine learning",
    "insights.export": "Export Report",
    "insights.askAI": "Ask AI Assistant",
    "insights.generated": "Insights Generated",
    "insights.followed": "Recommendations Followed",
    "insights.devScore": "Development Score",
    "insights.accuracy": "AI Accuracy",
    "insights.points": "points",
    "insights.aboveAverage": "Above average",
    "insights.excellent": "Excellent",
    "insights.assistant": "AI Parenting Assistant",
    "insights.assistantDesc": "Ask me anything about Odaisa's development, routines, or get personalized parenting advice based on her data.",
    "insights.typeQuestion": "Type your question here...",
    "insights.send": "Send",
    "insights.learning": "AI Learning Progress",
    "insights.mastered": "Mastered",
    "insights.learningStatus": "Learning",
    "insights.activeStatus": "Active",
    "insights.privacy": "Privacy & Data Security",
    "insights.privacyDesc": "All AI analysis is performed using encrypted data. Odaisa's information is never shared with third parties and you maintain full control over data usage.",
    "insights.viewPrivacy": "View Privacy Settings",
    "insights.suggestedActivities": "Suggested Activities",
    "insights.getMore": "Get More Suggestions",
    "insights.dailyQuote": "Parenting Insight of the Day",
    "insights.todayHighlights": "Today's Highlights",
    "insights.moodScore": "Mood Score",
    "insights.robotInteractions": "Robot Interactions",
    "insights.learnMore": "Learn More",
    "insights.dismiss": "Dismiss",
    "insights.startConversation": "Start Conversation",
    
    // Common
    "common.live": "LIVE",
    "common.filter": "Filter",
    "common.download": "Download",
    "common.share": "Share",
    "common.edit": "Edit",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.hrs": "hrs",
    "common.min": "min",
    "common.ago": "ago",
    "common.on": "On",
    "common.off": "Off"
  },
  es: {
    // Navigation
    "nav.overview": "Resumen",
    "nav.profile": "Perfil del Niño",
    "nav.development": "Desarrollo",
    "nav.routines": "Rutinas Diarias",
    "nav.robot": "Control del Robot",
    "nav.gallery": "Galería de Momentos",
    "nav.alerts": "Alertas",
    "nav.insights": "Recomendaciones IA",
    "nav.caregivers": "Cuidadores",
    "nav.settings": "Configuración",
    "nav.logout": "Cerrar Sesión",
    
    // Overview
    "overview.title": "¡Bienvenido de Nuevo! 👋",
    "overview.subtitle": "Esto es lo que está pasando con Odaisa hoy",
    "overview.sleep": "Sueño Anoche",
    "overview.meals": "Comidas Hoy",
    "overview.active": "Tiempo Activo",
    "overview.development": "Puntuación de Desarrollo",
    "overview.liveFeed": "Cámara en Vivo",
    "overview.milestones": "Hitos Recientes",
    "overview.activity": "Horas de Actividad Semanal",
    "overview.sleepPattern": "Patrón de Sueño Semanal",
    "overview.alerts": "Alertas y Actualizaciones Recientes",
    "overview.viewAll": "Ver Todo",
    "overview.currentActivity": "Actividad Actual:",
    "overview.playingWithToys": "Jugando con juguetes",
    "overview.firstSteps": "¡Primeros Pasos!",
    "overview.tookSteps": "Dio 5 pasos independientes",
    "overview.newWords": "Nuevas Palabras",
    "overview.wordsThisWeek": "+15 palabras esta semana",
    "overview.drawing": "Dibujo",
    "overview.firstCircle": "Primeras formas circulares",
    "overview.viewAllMilestones": "Ver Todos los Hitos",
    "overview.daysAgo": "días atrás",
    "overview.ongoing": "En curso",
    
    // Child Profile
    "profile.title": "Perfil del Niño",
    "profile.subtitle": "Información detallada y registros médicos",
    "profile.edit": "Editar Perfil",
    "profile.active": "Perfil Activo",
    "profile.childId": "ID del Niño:",
    "profile.healthy": "Saludable",
    "profile.dob": "Fecha de Nacimiento",
    "profile.height": "Altura",
    "profile.weight": "Peso",
    "profile.bloodType": "Tipo de Sangre",
    "profile.medical": "Información Médica",
    "profile.emergency": "Contactos de Emergencia",
    "profile.preferences": "Preferencias",
    "profile.caregivers": "Cuidadores",
    "profile.allergies": "Alergias",
    "profile.medications": "Medicamentos",
    "profile.conditions": "Condiciones Médicas",
    "profile.vaccinations": "Vacunas",
    "profile.upToDate": "Al día",
    "profile.lastCheckup": "Último Chequeo",
    "profile.nextCheckup": "Próximo Chequeo",
    "profile.pediatrician": "Pediatra",
    "profile.scheduleAppt": "Programar Cita",
    "profile.primary": "Principal",
    "profile.addContact": "Agregar Contacto de Emergencia",
    "profile.activities": "Actividades e Intereses",
    "profile.favoriteActivities": "Actividades Favoritas",
    "profile.favoriteFoods": "Comidas Favoritas",
    "profile.care": "Preferencias de Cuidado",
    "profile.napPrefs": "Preferencias de Siesta",
    "profile.comfortItems": "Artículos de Confort",
    "profile.temperament": "Temperamento",
    "profile.authorized": "Cuidadores Autorizados",
    "profile.manageAccess": "Administrar quién tiene acceso al panel de Odaisa y su información",
    "profile.invite": "Invitar Cuidador",
    "profile.fullAccess": "Acceso Completo",
    "profile.activeStatus": "Activo",
    
    // Development
    "dev.title": "Desarrollo y Progreso",
    "dev.subtitle": "Seguimiento de hitos y comparación con promedios de edad",
    "dev.stats": "Estadísticas de Progreso y Desarrollo",
    "dev.aiInsights": "Información impulsada por IA y seguimiento de hitos",
    "dev.advanced": "Análisis Avanzado",
    "dev.milestones": "Hitos del Desarrollo",
    "dev.growth": "Seguimiento de Crecimiento",
    "dev.activities": "Actividades Semanales",
    "dev.percentile": "percentil",
    "dev.recent": "Logro Reciente",
    "dev.prediction": "Predicción IA",
    "dev.next": "Próximo Hito",
    "dev.expected": "Esperado en",
    "dev.inProgress": "En progreso -",
    "dev.heightProgress": "Progreso de Altura",
    "dev.weightProgress": "Progreso de Peso",
    "dev.growthRate": "Tasa de Crecimiento",
    "dev.aboveAverage": "por encima del promedio",
    "dev.healthy": "saludable",
    "dev.totalPlaytime": "Tiempo Total de Juego Esta Semana",
    "dev.outdoor": "Actividades al Aire Libre",
    "dev.learningTime": "Tiempo de Aprendizaje",
    "dev.fromLastWeek": "desde la semana pasada",
    
    // Routines
    "routines.title": "Rutinas Diarias",
    "routines.subtitle": "Seguimiento de sueño, comidas y actividades diarias",
    "routines.export": "Exportar Informe",
    "routines.addEntry": "Agregar Entrada",
    "routines.remaining": "Horario Restante de Hoy",
    "routines.upcoming": "Próximo",
    "routines.sleep": "Sueño",
    "routines.feeding": "Alimentación",
    "routines.activities": "Actividades",
    "routines.lastNight": "Anoche",
    "routines.weekAverage": "Promedio Semanal",
    "routines.interruptions": "Interrupciones",
    "routines.excellent": "Excelente",
    "routines.consistent": "Consistente",
    "routines.belowAverage": "Por debajo del promedio",
    "routines.schedule": "Horario de Sueño (Anoche)",
    "routines.completed": "Completado",
    "routines.aiInsight": "Información IA",
    "routines.hydration": "Hidratación Hoy",
    "routines.todayMeals": "Comidas de Hoy",
    "routines.avgConsumption": "Consumo Promedio",
    "routines.pending": "Pendiente",
    "routines.high": "alto",
    "routines.medium": "medio",
    "routines.activitySummary": "Resumen de Actividad",
    "routines.totalActive": "Tiempo Activo Total",
    "routines.highEngagement": "Alto Compromiso",
    "routines.ofActivities": "de actividades",
    "routines.sleepSummary": "Resumen de Sueño",
    "routines.avgDuration": "Duración Promedio",
    "routines.consistency": "Puntuación de Consistencia",
    "routines.quality": "Calificación de Calidad",
    "routines.nutritionSummary": "Resumen de Nutrición",
    "routines.mealsCompleted": "Comidas Completadas",
    "routines.hydrationLevel": "Nivel de Hidratación",
    "routines.newFoods": "Nuevos Alimentos Probados",
    "routines.thisWeek": "esta semana",
    "routines.activitySummaryWeek": "Resumen de Actividad",
    "routines.totalActiveTime": "Tiempo Activo Total",
    "routines.engagementLevel": "Nivel de Compromiso",
    "routines.varietyScore": "Puntuación de Variedad",
    "routines.good": "Bueno",
    
    // Robot
    "robot.title": "Control del Robot",
    "robot.subtitle": "Comandar y programar tu asistente de cuidado infantil IA",
    "robot.settings": "Configuración del Robot",
    "robot.status": "Estado del Robot",
    "robot.online": "En Línea",
    "robot.battery": "Nivel de Batería",
    "robot.goodCharge": "Buena Carga",
    "robot.location": "Ubicación Actual",
    "robot.activeTime": "Tiempo Activo Hoy",
    "robot.quickCommands": "Comandos Rápidos",
    "robot.schedule": "Horario",
    "robot.storyTime": "Hora del Cuento",
    "robot.playMusic": "Reproducir Música",
    "robot.lullaby": "Canción de Cuna",
    "robot.playGames": "Jugar Juegos",
    "robot.active": "Activo",
    "robot.additionalControls": "Controles Adicionales",
    "robot.volume": "Nivel de Volumen",
    "robot.movement": "Modo de Movimiento",
    "robot.follow": "Seguir",
    "robot.nightMode": "Modo Nocturno",
    "robot.off": "Apagado",
    "robot.emergency": "Controles de Emergencia",
    "robot.stopAll": "Detener Todas las Actividades",
    "robot.callCaregiver": "Llamar al Cuidador",
    "robot.addSchedule": "Agregar Nuevo Elemento de Horario",
    "robot.scheduleOverview": "Resumen del Horario",
    "robot.completedTasks": "Completadas",
    "robot.pendingTasks": "Pendiente",
    "robot.upcomingTasks": "Próximas",
    "robot.tasks": "tareas",
    "robot.task": "tarea",
    "robot.activityLog": "Registro de Actividad de Hoy",
    "robot.viewHistory": "Ver Historial Completo de Actividad",
    "robot.maintenance": "Mantenimiento y Actualizaciones",
    "robot.lastMaintenance": "Último Mantenimiento",
    "robot.softwareVersion": "Versión de Software",
    "robot.nextUpdate": "Próxima Actualización",
    "robot.availableNow": "Disponible Ahora",
    "robot.updateSoftware": "Actualizar Software",
    "robot.quickActions": "Acciones Rápidas",
    "robot.calibrate": "Calibrar Sensores",
    "robot.testAudio": "Probar Sistema de Audio",
    "robot.resetHome": "Restablecer a Posición Inicial",
    "robot.emergencyStop": "Parada de Emergencia",
    
    // Gallery
    "gallery.title": "Galería de Momentos",
    "gallery.subtitle": "Recuerdos y momentos especiales capturados por IA",
    "gallery.download": "Descargar Seleccionados",
    "gallery.share": "Compartir Álbum",
    "gallery.milestones": "Hitos",
    "gallery.favorites": "Favoritos",
    "gallery.specialEvents": "Eventos Especiales",
    "gallery.items": "elementos",
    "gallery.recent": "Capturas Recientes",
    "gallery.today": "Hoy",
    "gallery.yesterday": "Ayer",
    "gallery.thisWeek": "Esta Semana",
    "gallery.thisMonth": "Este Mes",
    "gallery.loadMore": "Cargar Más Momentos",
    "gallery.storage": "Uso de Almacenamiento",
    "gallery.of": "de",
    "gallery.used": "usado",
    "gallery.available": "Disponible",
    "gallery.autoBackup": "Copia de seguridad automática activada",
    "gallery.capture": "Capturar Momento",
    "gallery.filter": "Filtrar",
    "gallery.total": "Momentos Totales",
    
    // Alerts
    "alerts.title": "Alertas y Notificaciones",
    "alerts.subtitle": "Monitorear eventos importantes y alertas de seguridad",
    "alerts.settings": "Configuración de Alertas",
    "alerts.markRead": "Marcar Todas como Leídas",
    "alerts.unread": "Alertas No Leídas",
    "alerts.new": "Nuevas",
    "alerts.safety": "Monitoreo de Seguridad",
    "alerts.allSystems": "Todos los Sistemas OK",
    "alerts.today": "Alertas de Hoy",
    "alerts.notifications": "Notificaciones",
    "alerts.milestonesWeek": "Hitos Esta Semana",
    "alerts.achievements": "Logros",
    "alerts.all": "Todas las Alertas",
    "alerts.safetyTab": "Seguridad",
    "alerts.milestonesTab": "Hitos",
    "alerts.settingsTab": "Configuración",
    "alerts.viewDetails": "Ver Detalles",
    "alerts.markAsRead": "Marcar Leída",
    "alerts.highPriority": "prioridad alta",
    "alerts.mediumPriority": "prioridad media",
    "alerts.lowPriority": "prioridad baja",
    "alerts.activeMonitors": "Monitores de Seguridad Activos",
    "alerts.lastTriggered": "Última activación:",
    "alerts.armed": "Armado",
    "alerts.emergencySettings": "Configuración de Alerta de Emergencia",
    "alerts.configureEmergency": "Configurar Alertas de Emergencia",
    "alerts.shareAchievement": "Compartir Logro",
    "alerts.viewProgress": "Ver Progreso",
    "alerts.noMilestones": "Aún no hay notificaciones de hitos",
    "alerts.notificationPrefs": "Preferencias de Notificación",
    "alerts.enabled": "Habilitado",
    "alerts.disabled": "Deshabilitado",
    "alerts.delivery": "Métodos de Entrega",
    "alerts.push": "Notificaciones Push",
    "alerts.email": "Alertas por Correo",
    "alerts.sms": "SMS (Solo Crítico)",
    
    // Insights
    "insights.title": "Recomendaciones e Información IA",
    "insights.subtitle": "Consejos personalizados impulsados por aprendizaje automático",
    "insights.export": "Exportar Informe",
    "insights.askAI": "Preguntar al Asistente IA",
    "insights.generated": "Información Generada",
    "insights.followed": "Recomendaciones Seguidas",
    "insights.devScore": "Puntuación de Desarrollo",
    "insights.accuracy": "Precisión IA",
    "insights.points": "puntos",
    "insights.aboveAverage": "Por encima del promedio",
    "insights.excellent": "Excelente",
    "insights.assistant": "Asistente Parental IA",
    "insights.assistantDesc": "Pregúntame cualquier cosa sobre el desarrollo de Odaisa, rutinas, u obtén consejos personalizados basados en sus datos.",
    "insights.typeQuestion": "Escribe tu pregunta aquí...",
    "insights.send": "Enviar",
    "insights.learning": "Progreso de Aprendizaje IA",
    "insights.mastered": "Dominado",
    "insights.learningStatus": "Aprendiendo",
    "insights.activeStatus": "Activo",
    "insights.privacy": "Privacidad y Seguridad de Datos",
    "insights.privacyDesc": "Todo el análisis de IA se realiza utilizando datos cifrados. La información de Odaisa nunca se comparte con terceros y mantienes el control total sobre el uso de los datos.",
    "insights.viewPrivacy": "Ver Configuración de Privacidad",
    "insights.suggestedActivities": "Actividades Sugeridas",
    "insights.getMore": "Obtener Más Sugerencias",
    "insights.dailyQuote": "Reflexión Parental del Día",
    "insights.todayHighlights": "Lo Más Destacado de Hoy",
    "insights.moodScore": "Puntuación de Ánimo",
    "insights.robotInteractions": "Interacciones con Robot",
    "insights.learnMore": "Aprender Más",
    "insights.dismiss": "Descartar",
    "insights.startConversation": "Iniciar Conversación",
    
    // Common
    "common.live": "EN VIVO",
    "common.filter": "Filtrar",
    "common.download": "Descargar",
    "common.share": "Compartir",
    "common.edit": "Editar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.add": "Agregar",
    "common.remove": "Remover",
    "common.close": "Cerrar",
    "common.confirm": "Confirmar",
    "common.hrs": "hrs",
    "common.min": "min",
    "common.ago": "hace",
    "common.on": "Encendido",
    "common.off": "Apagado"
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
